/**
 * Demo Data for Development & Testing
 *
 * This file contains mock data used when Supabase is not configured.
 * It allows the application to run in demo mode for testing and development.
 */

import type { Candidate, Activity, Interview } from '../types';

// Date helpers
const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const lastWeek = new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0];
const twoWeeksAgo = new Date(Date.now() - 14 * 86400000).toISOString().split('T')[0];

/**
 * Demo candidates representing various stages in the recruitment pipeline.
 * Includes Singapore Citizens (SC), Permanent Residents (PR), and foreign nationals.
 */
export const demoCandidates: Candidate[] = [
  {
    id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    date_received: new Date().toISOString(),
    full_name: 'Sarah Chen Wei Ling',
    email: 'sarah.chen@email.com',
    phone: '+65 9123 4567',
    source: 'Seek',
    applied_role: 'Senior Software Engineer',
    ai_score: 9,
    ai_category: 'Top Candidate',
    citizenship_status: 'SC',
    ai_summary: 'Strong candidate with 8 years of experience in full-stack development. Completed NS, local university graduate.',
    ai_reasoning: 'Extensive experience with React, Node.js, and AWS. Led multiple enterprise projects. Clear communication skills evident in application.',
    resume_url: 'https://example.com/resume/sarah-chen.pdf',
    current_status: 'interview_scheduled',
    assigned_recruiter: 'Shawn',
    matched_roles: ['Senior Software Engineer', 'Tech Lead'],
    client_submitted_to: 'DBS Bank',
    submission_date: lastWeek,
    interview_date: today,
    interview_outcome: null,
    offer_date: null,
    offer_status: null,
    start_date: null,
    contract_end_date: null,
    hourly_rate: null,
    bill_rate: null,
    placement_status: null,
    notes: 'Very responsive candidate. Preferred contact via WhatsApp.',
    last_contact_date: yesterday,
    next_action: 'Prepare for interview',
    next_action_date: today,
  },
  {
    id: '2',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    date_received: new Date(Date.now() - 3 * 86400000).toISOString(),
    full_name: 'Muhammad Rizal bin Ahmad',
    email: 'rizal.ahmad@email.com',
    phone: '+65 8765 4321',
    source: 'Indeed',
    applied_role: 'Data Analyst',
    ai_score: 8,
    ai_category: 'Top Candidate',
    citizenship_status: 'PR',
    ai_summary: 'Experienced data analyst with expertise in Python and SQL. PR holder with 5 years local experience.',
    ai_reasoning: 'Strong technical background with certifications in data analytics. Previous experience at local SMEs.',
    resume_url: 'https://example.com/resume/rizal.pdf',
    current_status: 'submitted_to_client',
    assigned_recruiter: 'Shawn',
    matched_roles: ['Data Analyst', 'Business Intelligence Analyst'],
    client_submitted_to: 'Grab Singapore',
    submission_date: yesterday,
    interview_date: null,
    interview_outcome: null,
    offer_date: null,
    offer_status: null,
    start_date: null,
    contract_end_date: null,
    hourly_rate: null,
    bill_rate: null,
    placement_status: null,
    notes: null,
    last_contact_date: yesterday,
    next_action: 'Follow up with client',
    next_action_date: today,
  },
  {
    id: '3',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    date_received: new Date(Date.now() - 5 * 86400000).toISOString(),
    full_name: 'Priya Krishnan',
    email: 'priya.k@email.com',
    phone: '+65 9876 5432',
    source: 'FastJobs',
    applied_role: 'Customer Service Representative',
    ai_score: 6,
    ai_category: 'Review',
    citizenship_status: 'Not Identified',
    ai_summary: 'Customer service experience with retail background. Citizenship status requires verification.',
    ai_reasoning: 'Good communication skills, but limited relevant experience. Needs citizenship verification.',
    resume_url: 'https://example.com/resume/priya.pdf',
    current_status: 'human_reviewed',
    assigned_recruiter: 'Shawn',
    matched_roles: ['Customer Service Representative'],
    client_submitted_to: null,
    submission_date: null,
    interview_date: null,
    interview_outcome: null,
    offer_date: null,
    offer_status: null,
    start_date: null,
    contract_end_date: null,
    hourly_rate: null,
    bill_rate: null,
    placement_status: null,
    notes: 'Need to verify citizenship status before proceeding.',
    last_contact_date: null,
    next_action: 'Call to verify citizenship',
    next_action_date: today,
  },
  {
    id: '4',
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    date_received: new Date(Date.now() - 10 * 86400000).toISOString(),
    full_name: 'Jason Tan Wei Ming',
    email: 'jason.tan@email.com',
    phone: '+65 9234 5678',
    source: 'LinkedIn',
    applied_role: 'Project Manager',
    ai_score: 9,
    ai_category: 'Top Candidate',
    citizenship_status: 'SC',
    ai_summary: 'PMP certified project manager with 10 years experience. NS completed, NUS graduate.',
    ai_reasoning: 'Excellent track record managing large-scale IT projects. Strong references from previous employers.',
    resume_url: 'https://example.com/resume/jason-tan.pdf',
    current_status: 'offer_extended',
    assigned_recruiter: 'Shawn',
    matched_roles: ['Project Manager', 'Program Manager'],
    client_submitted_to: 'Singtel',
    submission_date: twoWeeksAgo,
    interview_date: lastWeek,
    interview_outcome: 'Passed',
    offer_date: yesterday,
    offer_status: 'Pending',
    start_date: null,
    contract_end_date: null,
    hourly_rate: 75,
    bill_rate: 95,
    placement_status: null,
    notes: 'Awaiting response on offer. Candidate requested time to consider.',
    last_contact_date: yesterday,
    next_action: 'Follow up on offer decision',
    next_action_date: tomorrow,
  },
  {
    id: '5',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    date_received: new Date(Date.now() - 20 * 86400000).toISOString(),
    full_name: 'Amanda Lee Hui Wen',
    email: 'amanda.lee@email.com',
    phone: '+65 8123 4567',
    source: 'Seek',
    applied_role: 'UX Designer',
    ai_score: 8,
    ai_category: 'Top Candidate',
    citizenship_status: 'SC',
    ai_summary: 'Creative UX designer with strong portfolio. Singapore Citizen with NTU design degree.',
    ai_reasoning: 'Impressive portfolio showing user-centered design approach. Experience with enterprise applications.',
    resume_url: 'https://example.com/resume/amanda-lee.pdf',
    current_status: 'placement_started',
    assigned_recruiter: 'Shawn',
    matched_roles: ['UX Designer', 'UI/UX Designer'],
    client_submitted_to: 'OCBC Bank',
    submission_date: new Date(Date.now() - 18 * 86400000).toISOString().split('T')[0],
    interview_date: new Date(Date.now() - 14 * 86400000).toISOString().split('T')[0],
    interview_outcome: 'Passed',
    offer_date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
    offer_status: 'Accepted',
    start_date: today,
    contract_end_date: new Date(Date.now() + 180 * 86400000).toISOString().split('T')[0],
    hourly_rate: 55,
    bill_rate: 70,
    placement_status: 'Active',
    notes: 'Starting today at OCBC. Initial 6-month contract.',
    last_contact_date: yesterday,
    next_action: 'First week check-in',
    next_action_date: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
  },
  {
    id: '6',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    date_received: new Date(Date.now() - 2 * 86400000).toISOString(),
    full_name: 'David Ng Kah Heng',
    email: 'david.ng@email.com',
    phone: '+65 9345 6789',
    source: 'Indeed',
    applied_role: 'DevOps Engineer',
    ai_score: 4,
    ai_category: 'Rejected',
    citizenship_status: 'Foreign',
    ai_summary: 'Junior DevOps engineer. Not eligible - foreign national without work authorization.',
    ai_reasoning: 'While technical skills are present, candidate is a foreign national without valid work pass for Singapore.',
    resume_url: 'https://example.com/resume/david-ng.pdf',
    current_status: 'rejected_ai',
    assigned_recruiter: null,
    matched_roles: ['DevOps Engineer'],
    client_submitted_to: null,
    submission_date: null,
    interview_date: null,
    interview_outcome: null,
    offer_date: null,
    offer_status: null,
    start_date: null,
    contract_end_date: null,
    hourly_rate: null,
    bill_rate: null,
    placement_status: null,
    notes: 'Auto-rejected: Foreign national without work authorization.',
    last_contact_date: null,
    next_action: null,
    next_action_date: null,
  },
  {
    id: '7',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    date_received: new Date().toISOString(),
    full_name: 'Michelle Lim Jia Yi',
    email: 'michelle.lim@email.com',
    phone: '+65 9456 7890',
    source: 'Seek',
    applied_role: 'Business Analyst',
    ai_score: 7,
    ai_category: 'Review',
    citizenship_status: 'SC',
    ai_summary: 'Recent graduate with internship experience. Strong academic background from SMU.',
    ai_reasoning: 'Limited professional experience but strong potential. Good academic projects in business analytics.',
    resume_url: 'https://example.com/resume/michelle-lim.pdf',
    current_status: 'ai_screened',
    assigned_recruiter: null,
    matched_roles: ['Business Analyst', 'Junior Data Analyst'],
    client_submitted_to: null,
    submission_date: null,
    interview_date: null,
    interview_outcome: null,
    offer_date: null,
    offer_status: null,
    start_date: null,
    contract_end_date: null,
    hourly_rate: null,
    bill_rate: null,
    placement_status: null,
    notes: null,
    last_contact_date: null,
    next_action: 'Review application',
    next_action_date: today,
  },
  {
    id: '8',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    date_received: new Date(Date.now() - 7 * 86400000).toISOString(),
    full_name: 'Kevin Wong Jian Wei',
    email: 'kevin.wong@email.com',
    phone: '+65 9567 8901',
    source: 'Direct',
    applied_role: 'Systems Administrator',
    ai_score: 8,
    ai_category: 'Top Candidate',
    citizenship_status: 'SC',
    ai_summary: 'Experienced sysadmin with cloud certifications. Singapore Citizen, completed NS, Polytechnic graduate.',
    ai_reasoning: 'Strong technical skills with AWS and Azure certifications. Good experience with enterprise systems.',
    resume_url: 'https://example.com/resume/kevin-wong.pdf',
    current_status: 'shortlisted',
    assigned_recruiter: 'Shawn',
    matched_roles: ['Systems Administrator', 'Cloud Engineer'],
    client_submitted_to: null,
    submission_date: null,
    interview_date: null,
    interview_outcome: null,
    offer_date: null,
    offer_status: null,
    start_date: null,
    contract_end_date: null,
    hourly_rate: null,
    bill_rate: null,
    placement_status: null,
    notes: 'Good candidate, looking for suitable client match.',
    last_contact_date: yesterday,
    next_action: 'Find matching client opportunities',
    next_action_date: today,
  },
  {
    id: '9',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    date_received: new Date(Date.now() - 4 * 86400000).toISOString(),
    full_name: 'Rachel Goh Mei Ling',
    email: 'rachel.goh@email.com',
    phone: '+65 9678 9012',
    source: 'Referral',
    applied_role: 'Marketing Manager',
    ai_score: 9,
    ai_category: 'Top Candidate',
    citizenship_status: 'PR',
    ai_summary: 'Senior marketing professional with digital marketing expertise. PR holder with 8 years local experience.',
    ai_reasoning: 'Impressive track record in digital campaigns. Referral from trusted contact. Strong leadership experience.',
    resume_url: 'https://example.com/resume/rachel-goh.pdf',
    current_status: 'interview_completed',
    assigned_recruiter: 'Shawn',
    matched_roles: ['Marketing Manager', 'Digital Marketing Lead'],
    client_submitted_to: 'Shopee Singapore',
    submission_date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    interview_date: yesterday,
    interview_outcome: 'Pending',
    offer_date: null,
    offer_status: null,
    start_date: null,
    contract_end_date: null,
    hourly_rate: null,
    bill_rate: null,
    placement_status: null,
    notes: 'Interview went well. Client to provide feedback by end of week.',
    last_contact_date: yesterday,
    next_action: 'Follow up with client for feedback',
    next_action_date: tomorrow,
  },
  {
    id: '10',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    date_received: new Date(Date.now() - 1 * 86400000).toISOString(),
    full_name: 'Benjamin Teo Jun Hao',
    email: 'ben.teo@email.com',
    phone: '+65 9789 0123',
    source: 'FastJobs',
    applied_role: 'IT Support Specialist',
    ai_score: 7,
    ai_category: 'Review',
    citizenship_status: 'SC',
    ai_summary: 'IT support professional with helpdesk experience. Singapore Citizen with relevant certifications.',
    ai_reasoning: 'Solid technical support background. CompTIA A+ certified. Good communication skills noted in application.',
    resume_url: 'https://example.com/resume/ben-teo.pdf',
    current_status: 'new_application',
    assigned_recruiter: null,
    matched_roles: ['IT Support Specialist', 'Helpdesk Analyst'],
    client_submitted_to: null,
    submission_date: null,
    interview_date: null,
    interview_outcome: null,
    offer_date: null,
    offer_status: null,
    start_date: null,
    contract_end_date: null,
    hourly_rate: null,
    bill_rate: null,
    placement_status: null,
    notes: null,
    last_contact_date: null,
    next_action: 'Initial screening call',
    next_action_date: today,
  },
];

/**
 * Demo activities representing various candidate interactions.
 */
export const demoActivities: Activity[] = [
  {
    id: '1',
    created_at: new Date().toISOString(),
    candidate_id: '1',
    candidate_name: 'Sarah Chen Wei Ling',
    activity_date: new Date().toISOString(),
    activity_type: 'Interview Scheduled',
    direction: 'Outbound',
    channel: 'Email',
    subject: 'Interview Confirmation - DBS Bank',
    details: 'Sent interview confirmation details for DBS Bank interview scheduled for today at 2:00 PM.',
    related_job: 'Senior Software Engineer',
    related_client: 'DBS Bank',
    outcome: 'Confirmed',
    follow_up_required: true,
    follow_up_date: today,
    follow_up_action: 'Prepare candidate briefing',
    logged_by: 'Shawn',
  },
  {
    id: '2',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    candidate_id: '2',
    candidate_name: 'Muhammad Rizal bin Ahmad',
    activity_date: new Date(Date.now() - 86400000).toISOString(),
    activity_type: 'Submission',
    direction: 'Outbound',
    channel: 'Email',
    subject: 'Candidate Submission - Grab Singapore',
    details: 'Submitted candidate profile to Grab Singapore hiring manager for Data Analyst position.',
    related_job: 'Data Analyst',
    related_client: 'Grab Singapore',
    outcome: 'Pending Review',
    follow_up_required: true,
    follow_up_date: today,
    follow_up_action: 'Follow up with client',
    logged_by: 'Shawn',
  },
  {
    id: '3',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    candidate_id: '4',
    candidate_name: 'Jason Tan Wei Ming',
    activity_date: new Date(Date.now() - 86400000).toISOString(),
    activity_type: 'Offer Extended',
    direction: 'Outbound',
    channel: 'Phone',
    subject: 'Offer Discussion',
    details: 'Called to present offer from Singtel. Candidate is reviewing and requested 2 days to decide.',
    related_job: 'Project Manager',
    related_client: 'Singtel',
    outcome: 'Pending Decision',
    follow_up_required: true,
    follow_up_date: tomorrow,
    follow_up_action: 'Follow up on offer decision',
    logged_by: 'Shawn',
  },
  {
    id: '4',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    candidate_id: '9',
    candidate_name: 'Rachel Goh Mei Ling',
    activity_date: new Date(Date.now() - 86400000).toISOString(),
    activity_type: 'Interview Completed',
    direction: 'Internal',
    channel: 'System',
    subject: 'Interview with Shopee Singapore',
    details: 'Candidate completed first round interview with Shopee. Feedback from candidate was positive.',
    related_job: 'Marketing Manager',
    related_client: 'Shopee Singapore',
    outcome: 'Awaiting Client Feedback',
    follow_up_required: true,
    follow_up_date: tomorrow,
    follow_up_action: 'Get client feedback',
    logged_by: 'Shawn',
  },
  {
    id: '5',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    candidate_id: '5',
    candidate_name: 'Amanda Lee Hui Wen',
    activity_date: new Date(Date.now() - 86400000).toISOString(),
    activity_type: 'Onboarding',
    direction: 'Outbound',
    channel: 'WhatsApp',
    subject: 'First Day Reminder',
    details: 'Sent reminder about first day at OCBC. Confirmed reporting location and contact person.',
    related_job: 'UX Designer',
    related_client: 'OCBC Bank',
    outcome: 'Acknowledged',
    follow_up_required: false,
    follow_up_date: null,
    follow_up_action: null,
    logged_by: 'Shawn',
  },
  {
    id: '6',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    candidate_id: '8',
    candidate_name: 'Kevin Wong Jian Wei',
    activity_date: new Date(Date.now() - 3 * 86400000).toISOString(),
    activity_type: 'Phone Screen',
    direction: 'Outbound',
    channel: 'Phone',
    subject: 'Initial Phone Screening',
    details: 'Conducted phone screen. Candidate is actively looking and available to start in 2 weeks notice.',
    related_job: 'Systems Administrator',
    related_client: null,
    outcome: 'Shortlisted',
    follow_up_required: true,
    follow_up_date: today,
    follow_up_action: 'Find matching opportunities',
    logged_by: 'Shawn',
  },
  {
    id: '7',
    created_at: new Date().toISOString(),
    candidate_id: '7',
    candidate_name: 'Michelle Lim Jia Yi',
    activity_date: new Date().toISOString(),
    activity_type: 'AI Screening',
    direction: 'Internal',
    channel: 'System',
    subject: 'Application Received via Seek',
    details: 'New application received. AI screening completed with score 7/10. Recommended for human review.',
    related_job: 'Business Analyst',
    related_client: null,
    outcome: 'Pending Review',
    follow_up_required: true,
    follow_up_date: today,
    follow_up_action: 'Review application',
    logged_by: 'System',
  },
  {
    id: '8',
    created_at: new Date().toISOString(),
    candidate_id: '10',
    candidate_name: 'Benjamin Teo Jun Hao',
    activity_date: new Date().toISOString(),
    activity_type: 'AI Screening',
    direction: 'Internal',
    channel: 'System',
    subject: 'Application Received via FastJobs',
    details: 'New application received. AI screening completed with score 7/10. Recommended for review.',
    related_job: 'IT Support Specialist',
    related_client: null,
    outcome: 'New Application',
    follow_up_required: true,
    follow_up_date: today,
    follow_up_action: 'Initial screening call',
    logged_by: 'System',
  },
];

/**
 * Demo interviews representing various interview stages.
 */
export const demoInterviews: Interview[] = [
  {
    id: '1',
    created_at: new Date().toISOString(),
    candidate_id: '1',
    candidate_name: 'Sarah Chen Wei Ling',
    client_company: 'DBS Bank',
    job_role: 'Senior Software Engineer',
    interview_round: '1st',
    interview_type: 'Video',
    interview_date: today,
    interview_time: '14:00',
    duration_minutes: 60,
    location: 'Microsoft Teams',
    interviewer_name: 'James Wong',
    interviewer_title: 'Engineering Manager',
    prep_notes_sent: true,
    candidate_confirmed: true,
    status: 'Scheduled',
    outcome: null,
    client_feedback: null,
    candidate_feedback: null,
    next_steps: null,
    notes: 'Focus on system design and leadership experience.',
  },
  {
    id: '2',
    created_at: new Date().toISOString(),
    candidate_id: '9',
    candidate_name: 'Rachel Goh Mei Ling',
    client_company: 'Shopee Singapore',
    job_role: 'Marketing Manager',
    interview_round: '2nd',
    interview_type: 'In-Person',
    interview_date: tomorrow,
    interview_time: '10:00',
    duration_minutes: 90,
    location: 'Shopee Office, 5 Science Park Drive',
    interviewer_name: 'Linda Tan',
    interviewer_title: 'Head of Marketing',
    prep_notes_sent: false,
    candidate_confirmed: true,
    status: 'Scheduled',
    outcome: null,
    client_feedback: null,
    candidate_feedback: null,
    next_steps: null,
    notes: 'Final round with department head. Bring portfolio.',
  },
  {
    id: '3',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    candidate_id: '9',
    candidate_name: 'Rachel Goh Mei Ling',
    client_company: 'Shopee Singapore',
    job_role: 'Marketing Manager',
    interview_round: '1st',
    interview_type: 'Video',
    interview_date: yesterday,
    interview_time: '15:00',
    duration_minutes: 45,
    location: 'Zoom',
    interviewer_name: 'Mark Chen',
    interviewer_title: 'HR Manager',
    prep_notes_sent: true,
    candidate_confirmed: true,
    status: 'Completed',
    outcome: 'Passed',
    client_feedback: 'Strong communication skills. Good cultural fit.',
    candidate_feedback: 'Positive experience. Excited about the role.',
    next_steps: 'Proceed to second round',
    notes: null,
  },
  {
    id: '4',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    candidate_id: '4',
    candidate_name: 'Jason Tan Wei Ming',
    client_company: 'Singtel',
    job_role: 'Project Manager',
    interview_round: 'Final',
    interview_type: 'In-Person',
    interview_date: lastWeek,
    interview_time: '11:00',
    duration_minutes: 120,
    location: 'Singtel Office, Comcentre',
    interviewer_name: 'David Lim',
    interviewer_title: 'VP Technology',
    prep_notes_sent: true,
    candidate_confirmed: true,
    status: 'Completed',
    outcome: 'Passed',
    client_feedback: 'Excellent candidate. Strong PM skills and leadership.',
    candidate_feedback: 'Great interview. Impressed with company vision.',
    next_steps: 'Offer extended',
    notes: null,
  },
  {
    id: '5',
    created_at: new Date().toISOString(),
    candidate_id: '8',
    candidate_name: 'Kevin Wong Jian Wei',
    client_company: 'Standard Chartered',
    job_role: 'Cloud Engineer',
    interview_round: '1st',
    interview_type: 'Phone',
    interview_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    interview_time: '16:00',
    duration_minutes: 30,
    location: 'Phone Call',
    interviewer_name: 'Susan Lee',
    interviewer_title: 'Tech Recruiter',
    prep_notes_sent: false,
    candidate_confirmed: false,
    status: 'Scheduled',
    outcome: null,
    client_feedback: null,
    candidate_feedback: null,
    next_steps: null,
    notes: 'Initial screening call with recruiter.',
  },
];
